const BASE_URL = "https://gen.pollinations.ai";
const FALLBACK = ["zimage", "flux", "gptimage", "klein"];
const ALIASES = {"flux-schnell":"flux","flux schnell":"flux","flux.1 schnell":"flux","flux.1 kontext":"kontext","flux kontext":"kontext","kontext":"kontext","z-image":"zimage","gpt-image":"gptimage","gpt image":"gptimage","gpt-image-large":"gptimage-large"};
function getKey(){return process.env.POLLINATIONS_API_KEY || process.env.POLLINATIONS_KEY || process.env.POLLINATIONS_SECRET_KEY || "";}
function normModel(m){m=String(m||"zimage").trim().toLowerCase();return ALIASES[m] || m || "zimage";}
function clamp(v,min,max,fb){v=Number(v);if(!Number.isFinite(v))return fb;return Math.max(min,Math.min(max,Math.round(v)));}
function safeSize(w,h,model){w=clamp(w,256,1536,768);h=clamp(h,256,1536,1344);const r=w/h;if(r<.62)return{w:768,h:1344};if(r>1.62)return{w:1344,h:768};if(Math.abs(r-1)<.09)return{w:1024,h:1024};w=Math.round(w/64)*64;h=Math.round(h/64)*64;const maxArea=(model==="gptimage"||model==="gptimage-large")?1572864:1032192;if(w*h>maxArea){const s=Math.sqrt(maxArea/(w*h));w=Math.round((w*s)/64)*64;h=Math.round((h*s)/64)*64}return{w:Math.max(256,w),h:Math.max(256,h)}}
function slimPrompt(prompt,model){let txt=String(prompt||"").replace(/\s+/g," ").replace(/Negative prompt:/gi,"Avoid:").trim();const limit=(model==="gptimage"||model==="gptimage-large")?2600:1300;if(txt.length<=limit)return txt;const parts=txt.split(/[,.;|]+/).map(x=>x.trim()).filter(Boolean);const seen=new Set();let out="";for(const p of parts){const key=p.toLowerCase().replace(/[^a-z0-9]+/g," ").trim();if(!key||seen.has(key))continue;seen.add(key);const next=out?", "+p:p;if((out+next).length>limit-100)break;out+=next}return(out+", masterpiece, high detail, sharp focus").slice(0,limit)}
async function getImage(prompt,model,width,height,seed,quality,key){const params=new URLSearchParams({model,width:String(width),height:String(height)});if(["flux","zimage","klein","seedream5","seedream"].includes(model))params.set("seed",String(seed));if(["gptimage","gptimage-large","gpt-image-2"].includes(model))params.set("quality",quality==="hd"?"hd":"medium");const url=`${BASE_URL}/image/${encodeURIComponent(prompt)}?${params.toString()}`;return fetch(url,{method:"GET",headers:{Authorization:`Bearer ${key}`,Accept:"image/png,image/jpeg,image/webp,*/*"},cache:"no-store"})}
async function postImage(prompt,model,width,height,quality,key){return fetch(`${BASE_URL}/v1/images/generations`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${key}`},body:JSON.stringify({model,prompt,n:1,size:`${width}x${height}`,quality:quality==="hd"?"hd":"medium",response_format:"b64_json",user:"vaia-ai-studio"})})}
async function imageFromPost(r){const data=await r.json();const item=data?.data?.[0]||{};const b64=item.b64_json||item.b64||data.b64_json;const url=item.url||data.url;if(b64){const clean=String(b64).replace(/^data:image\/[a-z0-9+.-]+;base64,/i,"");return{buffer:Buffer.from(clean,"base64"),type:"image/png"}}if(url){const rr=await fetch(url,{cache:"no-store"});if(!rr.ok)throw new Error("Image URL gagal dibaca.");return{buffer:Buffer.from(await rr.arrayBuffer()),type:rr.headers.get("content-type")||"image/png"}}throw new Error("Response gambar kosong.")}
function sendErr(res,status,msg,debug){return res.status(status).json({error:msg,debug:debug?String(debug).slice(0,700):undefined})}
module.exports=async function handler(req,res){if(req.method!=="POST"){res.setHeader("Allow","POST");return sendErr(res,405,"Method not allowed.")}const key=getKey();if(!key)return sendErr(res,500,"Engine belum tersambung. Cek pengaturan Vercel lalu Redeploy.");try{const body=typeof req.body==="string"?JSON.parse(req.body):(req.body||{});const basePrompt=String(body.prompt||"").trim();if(!basePrompt)return sendErr(res,400,"Prompt kosong.");const first=normModel(body.model||"zimage");const models=[...new Set([first,...FALLBACK])];const seed=clamp(body.seed,-1,2147483647,-1);const quality=String(body.quality||"balanced");const errors=[];for(const model of models){const size=safeSize(body.width,body.height,model);const prompt=slimPrompt(basePrompt,model);try{let up=await getImage(prompt,model,size.w,size.h,seed,quality,key);let type=up.headers.get("content-type")||"";if(up.ok&&type.startsWith("image/")){const buffer=Buffer.from(await up.arrayBuffer());res.setHeader("Content-Type",type);res.setHeader("Cache-Control","no-store");res.setHeader("X-Content-Type-Options","nosniff");res.setHeader("X-VAIA-Model-Used",model);res.setHeader("X-VAIA-Size-Used",`${size.w}x${size.h}`);return res.status(200).send(buffer)}const t1=await up.text().catch(()=>"");errors.push(`${model} GET ${up.status}: ${t1.slice(0,180)}`);if(["gptimage","gptimage-large","zimage","flux","klein"].includes(model)){up=await postImage(prompt,model,size.w,size.h,quality,key);type=up.headers.get("content-type")||"";if(up.ok&&type.includes("application/json")){const img=await imageFromPost(up);res.setHeader("Content-Type",img.type);res.setHeader("Cache-Control","no-store");res.setHeader("X-Content-Type-Options","nosniff");res.setHeader("X-VAIA-Model-Used",model);res.setHeader("X-VAIA-Size-Used",`${size.w}x${size.h}`);return res.status(200).send(img.buffer)}const t2=await up.text().catch(()=>"");errors.push(`${model} POST ${up.status}: ${t2.slice(0,180)}`)}}catch(e){errors.push(`${model}: ${e.message||e}`)}}return sendErr(res,502,"Semua model sedang gagal. Coba prompt lebih pendek atau pilih Z-Image.",errors.join(" | "))}catch(e){return sendErr(res,500,e.message||"Server error.")}};
